name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup repo
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

    - name: Check types
      run: deno check mod.ts

    - name: Run tests
      run: deno test --allow-all --coverage=cov/

    - name: Generate coverage report
      run: deno coverage --lcov cov/ > coverage.lcov

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.lcov

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Setup repo
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Publish to JSR
      run: deno publish